const githubUrl = "https://github.com/GuilhermeBrightmore/Discord-2";
const downloadUrl = process.env.NEXT_PUBLIC_DOWNLOAD_URL ?? `${githubUrl}/releases/latest`;

export default function Home() {
  return <main>
    <nav className="site-nav"><a className="site-brand" href="#inicio"><img src="/fungocord.png" alt="" /><span>FungoCord</span></a><div><a href="#recursos">Recursos</a><a href={githubUrl} target="_blank" rel="noreferrer">GitHub</a><a className="nav-download" href={downloadUrl}>Download</a></div></nav>
    <section className="hero" id="inicio"><div className="hero-copy"><span className="hero-kicker"><i /> CONVERSAS QUE CRIAM RAÍZES</span><h1>Seu lugar para<br /><em>conversar e jogar.</em></h1><p>Mensagens em tempo real, servidores, chamadas com vídeo e compartilhamento de tela. Tudo reunido em uma experiência leve, bonita e independente.</p><div className="hero-actions"><a className="download-button" href={downloadUrl}><DownloadIcon /> Baixar para Windows</a><a className="ghost-button" href={githubUrl} target="_blank" rel="noreferrer"><GithubIcon /> Ver no GitHub</a></div><small>Windows 10 e 11 · Atualizações automáticas · Instalador e versão portátil</small></div><AppPreview /></section>
    <section className="feature-section" id="recursos"><div className="section-heading"><span>FEITO PARA FICAR JUNTO</span><h2>O essencial, sem distrações.</h2><p>Uma casa digital para grupos pequenos, comunidades e noites de jogo.</p></div><div className="feature-grid"><Feature icon="✦" title="Mensagens instantâneas" text="Canais e conversas diretas sincronizados em tempo real." /><Feature icon="◉" title="Chamadas completas" text="Veja todos na sala, estados de microfone, câmera e quem está falando." /><Feature icon="▣" title="Compartilhe sua tela" text="Escolha janela, monitor, resolução, áudio e até 60 FPS." /><Feature icon="↻" title="Sempre atualizado" text="Novas versões chegam pelo próprio aplicativo, sem reinstalação manual." /><Feature icon="⌁" title="Volume individual" text="Ajuste localmente cada pessoa ou transmissão sem afetar os demais." /><Feature icon="◇" title="Sua comunidade" text="Crie servidores, canais de texto e voz, convites e permissões." /></div></section>
    <section className="download-section"><img src="/fungocord.png" alt="Cogumelo do FungoCord" /><div><span>PRONTO PARA COMEÇAR?</span><h2>Encontre sua turma no FungoCord.</h2><p>Baixe a versão mais recente ou acompanhe o código e os lançamentos pelo GitHub.</p></div><a className="download-button" href={downloadUrl}><DownloadIcon /> Baixar FungoCord</a></section>
    <footer className="site-footer"><a className="site-brand" href="#inicio"><img src="/fungocord.png" alt="" /><span>FungoCord</span></a><div className="footer-links"><a href={downloadUrl}>Download</a><a href={githubUrl} target="_blank" rel="noreferrer">GitHub</a><a href="/api/health">Status da API</a></div><p>© 2026 FungoCord · Créditos: GuilhermeBrightmore</p></footer>
  </main>;
}

function AppPreview() {
  const callers = ["GA", "NT", "PF"];
  return <div className="app-preview"><div className="preview-glow" /><div className="preview-window"><div className="preview-rail"><img src="/fungocord.png" alt="" /><b>FU</b><b>GC</b><span>+</span></div><div className="preview-sidebar"><header>Cogumelos <span>⌄</span></header><small>CANAIS DE TEXTO</small><p># geral</p><p className="selected"># jogos</p><small>CANAIS DE VOZ</small><p>◉ Bate-papo</p><div className="preview-callers">{callers.map((caller, index) => <span key={caller}><i className={`avatar color-${index}`}>{caller}</i>{index === 1 ? "Nat" : index === 2 ? "Pantera" : "Guilherme"}<b>{index === 0 ? "◉" : "⌁"}</b></span>)}</div></div><div className="preview-chat"><header><b># jogos</b><span>FungoCord</span></header><div className="preview-messages"><Message avatar="GU" name="Guilherme" text="Vamos entrar na call?" /><Message avatar="NA" name="Nat" text="Já estou conectada 🍄" /><div className="preview-share"><span>TRANSMISSÃO AO VIVO</span><strong>Compartilhando a tela em 60 FPS</strong><i /></div></div><div className="preview-composer">Conversar em #jogos <b>➤</b></div></div><div className="preview-pip"><header><span><i /> Bate-papo</span><b>↗</b></header><div>{callers.slice(0, 2).map((caller, index) => <span className={`pip-user color-${index}`} key={caller}>{caller}<i>⌁</i></span>)}</div><footer>3 conectados</footer></div></div></div>;
}

function Message({ avatar, name, text }: { avatar: string; name: string; text: string }) { return <div className="preview-message"><i>{avatar}</i><span><b>{name}</b><p>{text}</p></span></div>; }
function Feature({ icon, title, text }: { icon: string; title: string; text: string }) { return <article><i>{icon}</i><h3>{title}</h3><p>{text}</p></article>; }
function DownloadIcon() { return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3v12m0 0 5-5m-5 5-5-5M5 20h14" /></svg>; }
function GithubIcon() { return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M15 22v-4c.1-1-.4-2-1-2.5 3 0 6-.7 6-6.1A4.7 4.7 0 0 0 18.7 6c.1-.9-.1-2-.6-3 0 0-1-.3-3.5 1.3a12 12 0 0 0-6.2 0C6 2.7 5 3 5 3a6 6 0 0 0-.7 3A4.7 4.7 0 0 0 3 9.4c0 5.4 3 6.1 6 6.1-.4.4-.8 1-.9 1.7-.8.4-2.8 1-4-1.1 0 0-.8-1.5-2.2-1.6 0 0-1.4 0-.1.9 0 0 1 .4 1.6 1.8 0 0 .9 2.8 4.7 1.9V22" /></svg>; }
