-- FungoCord: convites profundos, respostas, cargos, moderacao, auditoria e comandos de voz.
-- Esta migracao e idempotente para poder ser reaplicada com seguranca.

alter table public.messages add column if not exists reply_to_id uuid;
alter table public.direct_messages add column if not exists reply_to_id uuid;

do $$ begin
  alter table public.messages
    add constraint messages_reply_to_id_fkey foreign key (reply_to_id) references public.messages(id) on delete set null;
exception when duplicate_object then null;
end $$;

do $$ begin
  alter table public.direct_messages
    add constraint direct_messages_reply_to_id_fkey foreign key (reply_to_id) references public.direct_messages(id) on delete set null;
exception when duplicate_object then null;
end $$;

create table if not exists public.server_roles (
  id uuid primary key default gen_random_uuid(),
  server_id uuid not null references public.servers(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 64),
  color text not null default '#8b5cf6' check (color ~ '^#[0-9a-fA-F]{6}$'),
  position integer not null default 1 check (position >= 0),
  permissions jsonb not null default '{}'::jsonb,
  is_everyone boolean not null default false,
  created_at timestamptz not null default now(),
  unique (id, server_id),
  unique (server_id, name)
);
create unique index if not exists server_roles_everyone_idx on public.server_roles(server_id) where is_everyone;
create index if not exists server_roles_server_position_idx on public.server_roles(server_id, position desc);

create table if not exists public.member_roles (
  server_id uuid not null,
  user_id uuid not null,
  role_id uuid not null,
  assigned_by uuid references public.profiles(id) on delete set null,
  assigned_at timestamptz not null default now(),
  primary key (server_id, user_id, role_id),
  foreign key (server_id, user_id) references public.server_members(server_id, user_id) on delete cascade,
  foreign key (role_id, server_id) references public.server_roles(id, server_id) on delete cascade
);

create table if not exists public.server_bans (
  server_id uuid not null references public.servers(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  moderator_id uuid references public.profiles(id) on delete set null,
  reason text check (reason is null or char_length(reason) <= 500),
  created_at timestamptz not null default now(),
  primary key (server_id, user_id)
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  server_id uuid not null references public.servers(id) on delete cascade,
  actor_id uuid references public.profiles(id) on delete set null,
  target_user_id uuid references public.profiles(id) on delete set null,
  action text not null,
  target_type text,
  target_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists audit_logs_server_created_idx on public.audit_logs(server_id, created_at desc);

create table if not exists public.voice_commands (
  id uuid primary key default gen_random_uuid(),
  server_id uuid not null references public.servers(id) on delete cascade,
  target_user_id uuid not null references public.profiles(id) on delete cascade,
  actor_id uuid references public.profiles(id) on delete set null,
  action text not null check (action in ('disconnect', 'move')),
  channel_id uuid references public.channels(id) on delete cascade,
  created_at timestamptz not null default now(),
  check ((action = 'disconnect' and channel_id is null) or (action = 'move' and channel_id is not null))
);
create index if not exists voice_commands_target_idx on public.voice_commands(target_user_id, created_at desc);

create or replace function public.ensure_everyone_role(target_server uuid) returns void
language plpgsql security definer set search_path = public
as $$
begin
  insert into public.server_roles(server_id, name, color, position, permissions, is_everyone)
  values (target_server, '@everyone', '#99aab5', 0, '{}'::jsonb, true)
  on conflict do nothing;
end; $$;

create or replace function public.ensure_server_default_role() returns trigger
language plpgsql security definer set search_path = public
as $$ begin perform public.ensure_everyone_role(new.id); return new; end; $$;

drop trigger if exists servers_default_role on public.servers;
create trigger servers_default_role after insert on public.servers
for each row execute function public.ensure_server_default_role();

select public.ensure_everyone_role(id) from public.servers;

create or replace function public.has_server_permission(
  target_server uuid,
  requested_permission text,
  target_user uuid default auth.uid()
) returns boolean
language sql stable security definer set search_path = public
as $$
  select exists (
    select 1
    from public.server_members member
    where member.server_id = target_server
      and member.user_id = target_user
      and (
        member.role in ('owner', 'admin')
        or exists (
          select 1
          from public.member_roles membership
          join public.server_roles role on role.id = membership.role_id and role.server_id = membership.server_id
          where membership.server_id = member.server_id
            and membership.user_id = member.user_id
            and (
              coalesce((role.permissions->>'administrator')::boolean, false)
              or coalesce((role.permissions->>requested_permission)::boolean, false)
            )
        )
      )
  );
$$;

create or replace function public.can_manage_server(target_server uuid, target_user uuid default auth.uid()) returns boolean
language sql stable security definer set search_path = public
as $$ select public.has_server_permission(target_server, 'manage_server', target_user); $$;

create or replace function public.member_hierarchy(target_server uuid, target_user uuid) returns integer
language sql stable security definer set search_path = public
as $$
  select case member.role
    when 'owner' then 2147483647
    when 'admin' then 1000000000
    else coalesce((
      select max(role.position)
      from public.member_roles membership
      join public.server_roles role on role.id = membership.role_id and role.server_id = membership.server_id
      where membership.server_id = target_server and membership.user_id = target_user
    ), 0)
  end
  from public.server_members member
  where member.server_id = target_server and member.user_id = target_user;
$$;

create or replace function public.can_act_on_member(target_server uuid, target_user uuid, actor uuid default auth.uid()) returns boolean
language sql stable security definer set search_path = public
as $$
  select actor <> target_user
    and coalesce(public.member_hierarchy(target_server, actor), -1) > coalesce(public.member_hierarchy(target_server, target_user), 2147483647);
$$;

create or replace function public.reply_belongs_to_channel(target_reply uuid, target_channel uuid) returns boolean
language sql stable security definer set search_path = public
as $$ select target_reply is null or exists(select 1 from public.messages where id = target_reply and channel_id = target_channel); $$;

create or replace function public.reply_belongs_to_direct(target_reply uuid, target_conversation uuid) returns boolean
language sql stable security definer set search_path = public
as $$ select target_reply is null or exists(select 1 from public.direct_messages where id = target_reply and conversation_id = target_conversation); $$;

create or replace function public.write_audit(
  target_server uuid,
  audit_action text,
  audit_target_user uuid default null,
  audit_target_type text default null,
  audit_target_id text default null,
  audit_metadata jsonb default '{}'::jsonb
) returns void
language plpgsql security definer set search_path = public
as $$
begin
  insert into public.audit_logs(server_id, actor_id, target_user_id, action, target_type, target_id, metadata)
  values (target_server, auth.uid(), audit_target_user, audit_action, audit_target_type, audit_target_id, coalesce(audit_metadata, '{}'::jsonb));
end; $$;

create or replace function public.create_server_role(
  target_server uuid,
  role_name text,
  role_color text,
  role_permissions jsonb default '{}'::jsonb
) returns uuid
language plpgsql security definer set search_path = public
as $$
declare new_role uuid; next_position integer;
begin
  if not public.has_server_permission(target_server, 'manage_roles') then raise exception 'Sem permissao para gerenciar cargos'; end if;
  select coalesce(max(position), 0) + 1 into next_position from public.server_roles where server_id = target_server;
  insert into public.server_roles(server_id, name, color, position, permissions)
  values (target_server, trim(role_name), lower(role_color), next_position, coalesce(role_permissions, '{}'::jsonb))
  returning id into new_role;
  perform public.write_audit(target_server, 'role.created', null, 'role', new_role::text, jsonb_build_object('name', trim(role_name)));
  return new_role;
end; $$;

create or replace function public.update_server_role(
  target_role uuid,
  role_name text,
  role_color text,
  role_position integer,
  role_permissions jsonb
) returns void
language plpgsql security definer set search_path = public
as $$
declare role_record public.server_roles%rowtype;
begin
  select * into role_record from public.server_roles where id = target_role;
  if role_record.id is null then raise exception 'Cargo nao encontrado'; end if;
  if role_record.is_everyone then
    if role_position <> 0 then raise exception 'O cargo @everyone deve permanecer na base'; end if;
  end if;
  if not public.has_server_permission(role_record.server_id, 'manage_roles') then raise exception 'Sem permissao para gerenciar cargos'; end if;
  if public.member_hierarchy(role_record.server_id, auth.uid()) <= greatest(role_record.position, role_position) then raise exception 'Cargo acima da sua hierarquia'; end if;
  update public.server_roles set
    name = case when is_everyone then '@everyone' else trim(role_name) end,
    color = lower(role_color),
    position = case when is_everyone then 0 else greatest(role_position, 1) end,
    permissions = coalesce(role_permissions, '{}'::jsonb)
  where id = target_role;
  perform public.write_audit(role_record.server_id, 'role.updated', null, 'role', target_role::text, jsonb_build_object('name', trim(role_name), 'position', role_position));
end; $$;

create or replace function public.delete_server_role(target_role uuid) returns void
language plpgsql security definer set search_path = public
as $$
declare role_record public.server_roles%rowtype;
begin
  select * into role_record from public.server_roles where id = target_role;
  if role_record.id is null then return; end if;
  if role_record.is_everyone then raise exception 'O cargo @everyone nao pode ser apagado'; end if;
  if not public.has_server_permission(role_record.server_id, 'manage_roles') then raise exception 'Sem permissao para gerenciar cargos'; end if;
  if public.member_hierarchy(role_record.server_id, auth.uid()) <= role_record.position then raise exception 'Cargo acima da sua hierarquia'; end if;
  delete from public.server_roles where id = target_role;
  perform public.write_audit(role_record.server_id, 'role.deleted', null, 'role', target_role::text, jsonb_build_object('name', role_record.name));
end; $$;

create or replace function public.assign_server_role(target_server uuid, target_user uuid, target_role uuid) returns void
language plpgsql security definer set search_path = public
as $$
declare selected_role public.server_roles%rowtype;
begin
  select * into selected_role from public.server_roles where id = target_role and server_id = target_server;
  if selected_role.id is null or selected_role.is_everyone then raise exception 'Cargo invalido'; end if;
  if not public.has_server_permission(target_server, 'manage_roles') then raise exception 'Sem permissao para gerenciar cargos'; end if;
  if not public.can_act_on_member(target_server, target_user) or public.member_hierarchy(target_server, auth.uid()) <= selected_role.position then raise exception 'Hierarquia insuficiente'; end if;
  insert into public.member_roles(server_id, user_id, role_id, assigned_by)
  values (target_server, target_user, target_role, auth.uid()) on conflict do nothing;
  perform public.write_audit(target_server, 'role.assigned', target_user, 'role', target_role::text, jsonb_build_object('name', selected_role.name));
end; $$;

create or replace function public.remove_server_role(target_server uuid, target_user uuid, target_role uuid) returns void
language plpgsql security definer set search_path = public
as $$
declare selected_role public.server_roles%rowtype;
begin
  select * into selected_role from public.server_roles where id = target_role and server_id = target_server;
  if selected_role.id is null then return; end if;
  if not public.has_server_permission(target_server, 'manage_roles') then raise exception 'Sem permissao para gerenciar cargos'; end if;
  if not public.can_act_on_member(target_server, target_user) or public.member_hierarchy(target_server, auth.uid()) <= selected_role.position then raise exception 'Hierarquia insuficiente'; end if;
  delete from public.member_roles where server_id = target_server and user_id = target_user and role_id = target_role;
  perform public.write_audit(target_server, 'role.removed', target_user, 'role', target_role::text, jsonb_build_object('name', selected_role.name));
end; $$;

create or replace function public.kick_server_member(target_server uuid, target_user uuid, reason text default null) returns void
language plpgsql security definer set search_path = public
as $$
begin
  if not public.has_server_permission(target_server, 'kick_members') then raise exception 'Sem permissao para expulsar membros'; end if;
  if not public.can_act_on_member(target_server, target_user) then raise exception 'Hierarquia insuficiente'; end if;
  perform public.write_audit(target_server, 'member.kicked', target_user, 'member', target_user::text, jsonb_build_object('reason', nullif(trim(reason), '')));
  delete from public.server_members where server_id = target_server and user_id = target_user;
end; $$;

create or replace function public.ban_server_member(target_server uuid, target_user uuid, reason text default null) returns void
language plpgsql security definer set search_path = public
as $$
begin
  if not public.has_server_permission(target_server, 'ban_members') then raise exception 'Sem permissao para banir membros'; end if;
  if not public.can_act_on_member(target_server, target_user) then raise exception 'Hierarquia insuficiente'; end if;
  insert into public.server_bans(server_id, user_id, moderator_id, reason)
  values (target_server, target_user, auth.uid(), nullif(trim(reason), ''))
  on conflict (server_id, user_id) do update set moderator_id = excluded.moderator_id, reason = excluded.reason, created_at = now();
  perform public.write_audit(target_server, 'member.banned', target_user, 'member', target_user::text, jsonb_build_object('reason', nullif(trim(reason), '')));
  delete from public.server_members where server_id = target_server and user_id = target_user;
end; $$;

create or replace function public.unban_server_member(target_server uuid, target_user uuid) returns void
language plpgsql security definer set search_path = public
as $$
begin
  if not public.has_server_permission(target_server, 'ban_members') then raise exception 'Sem permissao para remover banimento'; end if;
  delete from public.server_bans where server_id = target_server and user_id = target_user;
  perform public.write_audit(target_server, 'member.unbanned', target_user, 'member', target_user::text);
end; $$;

create or replace function public.issue_voice_command(
  target_server uuid,
  target_user uuid,
  command_action text,
  target_channel uuid default null
) returns uuid
language plpgsql security definer set search_path = public
as $$
declare command_id uuid;
begin
  if command_action not in ('disconnect', 'move') then raise exception 'Comando de voz invalido'; end if;
  if command_action = 'disconnect' and not public.has_server_permission(target_server, 'disconnect_members') then raise exception 'Sem permissao para desconectar membros'; end if;
  if command_action = 'move' and not public.has_server_permission(target_server, 'move_members') then raise exception 'Sem permissao para mover membros'; end if;
  if not public.can_act_on_member(target_server, target_user) then raise exception 'Hierarquia insuficiente'; end if;
  if command_action = 'move' and not exists(select 1 from public.channels where id = target_channel and server_id = target_server and kind = 'voice') then raise exception 'Canal de voz invalido'; end if;
  insert into public.voice_commands(server_id, target_user_id, actor_id, action, channel_id)
  values (target_server, target_user, auth.uid(), command_action, case when command_action = 'move' then target_channel else null end)
  returning id into command_id;
  perform public.write_audit(target_server, 'voice.' || command_action, target_user, 'voice', coalesce(target_channel::text, target_user::text));
  return command_id;
end; $$;

create or replace function public.join_server(invite_code text) returns uuid
language plpgsql security definer set search_path = public
as $$
declare target_server uuid; already_member boolean;
begin
  if auth.uid() is null then raise exception 'Nao autenticado'; end if;
  select server_id into target_server from public.invites
  where lower(code) = lower(trim(invite_code))
    and (expires_at is null or expires_at > now())
    and (max_uses is null or uses < max_uses)
  for update;
  if target_server is null then raise exception 'Convite invalido ou expirado'; end if;
  if exists(select 1 from public.server_bans where server_id = target_server and user_id = auth.uid()) then raise exception 'Voce esta banido deste servidor'; end if;
  select public.is_server_member(target_server) into already_member;
  insert into public.server_members(server_id, user_id) values (target_server, auth.uid()) on conflict do nothing;
  if not already_member then
    update public.invites set uses = uses + 1 where lower(code) = lower(trim(invite_code));
    perform public.write_audit(target_server, 'member.joined', auth.uid(), 'member', auth.uid()::text);
  end if;
  return target_server;
end; $$;

create or replace function public.audit_server_resource_change() returns trigger
language plpgsql security definer set search_path = public
as $$
declare target_server uuid; action_name text; resource_id text; details jsonb;
begin
  if tg_table_name = 'channels' then
    target_server := coalesce(new.server_id, old.server_id);
    resource_id := coalesce(new.id, old.id)::text;
    details := jsonb_build_object('name', coalesce(new.name, old.name), 'kind', coalesce(new.kind, old.kind));
  elsif tg_table_name = 'invites' then
    target_server := coalesce(new.server_id, old.server_id);
    resource_id := coalesce(new.code, old.code);
    details := '{}'::jsonb;
  else
    target_server := coalesce(new.id, old.id);
    resource_id := target_server::text;
    details := jsonb_build_object('name', coalesce(new.name, old.name));
  end if;
  action_name := rtrim(tg_table_name, 's') || '.' || lower(tg_op);
  perform public.write_audit(target_server, action_name, null, tg_table_name, resource_id, details);
  if tg_op = 'DELETE' then return old; end if;
  return new;
end; $$;

drop trigger if exists audit_channels on public.channels;
create trigger audit_channels after insert or update or delete on public.channels
for each row execute function public.audit_server_resource_change();
drop trigger if exists audit_invites on public.invites;
create trigger audit_invites after insert or delete on public.invites
for each row execute function public.audit_server_resource_change();
drop trigger if exists audit_servers on public.servers;
create trigger audit_servers after update on public.servers
for each row execute function public.audit_server_resource_change();

alter table public.server_roles enable row level security;
alter table public.member_roles enable row level security;
alter table public.server_bans enable row level security;
alter table public.audit_logs enable row level security;
alter table public.voice_commands enable row level security;

drop policy if exists "server_roles_read" on public.server_roles;
drop policy if exists "member_roles_read" on public.member_roles;
drop policy if exists "server_bans_read" on public.server_bans;
drop policy if exists "audit_logs_read" on public.audit_logs;
drop policy if exists "voice_commands_read_target" on public.voice_commands;
drop policy if exists "voice_commands_delete_target" on public.voice_commands;

create policy "server_roles_read" on public.server_roles for select to authenticated using (public.is_server_member(server_id));
create policy "member_roles_read" on public.member_roles for select to authenticated using (public.is_server_member(server_id));
create policy "server_bans_read" on public.server_bans for select to authenticated using (public.has_server_permission(server_id, 'ban_members'));
create policy "audit_logs_read" on public.audit_logs for select to authenticated using (public.has_server_permission(server_id, 'view_audit_log'));
create policy "voice_commands_read_target" on public.voice_commands for select to authenticated using (target_user_id = auth.uid());
create policy "voice_commands_delete_target" on public.voice_commands for delete to authenticated using (target_user_id = auth.uid());

drop policy if exists "servers_update_manager" on public.servers;
drop policy if exists "members_delete_manager" on public.server_members;
drop policy if exists "channels_write_manager" on public.channels;
drop policy if exists "channels_update_manager" on public.channels;
drop policy if exists "channels_delete_manager" on public.channels;
drop policy if exists "messages_insert_self" on public.messages;
drop policy if exists "messages_delete_author" on public.messages;
drop policy if exists "invites_insert_manager" on public.invites;
drop policy if exists "invites_delete_manager" on public.invites;

create policy "servers_update_manager" on public.servers for update to authenticated
using (public.has_server_permission(id, 'manage_server')) with check (public.has_server_permission(id, 'manage_server'));
create policy "channels_write_manager" on public.channels for insert to authenticated
with check (public.has_server_permission(server_id, 'manage_channels'));
create policy "channels_update_manager" on public.channels for update to authenticated
using (public.has_server_permission(server_id, 'manage_channels')) with check (public.has_server_permission(server_id, 'manage_channels'));
create policy "channels_delete_manager" on public.channels for delete to authenticated
using (public.has_server_permission(server_id, 'manage_channels'));
create policy "messages_insert_self" on public.messages for insert to authenticated
with check (
  author_id = auth.uid() and public.is_channel_member(channel_id)
  and (
    body !~* '(^|[[:space:]])@everyone([^a-z0-9_.]|$)'
    or public.has_server_permission((select server_id from public.channels where id = channel_id), 'mention_everyone')
  )
  and public.reply_belongs_to_channel(reply_to_id, channel_id)
);
create policy "messages_delete_author" on public.messages for delete to authenticated
using (
  author_id = auth.uid()
  or public.has_server_permission((select server_id from public.channels where id = channel_id), 'manage_messages')
);
create policy "invites_insert_manager" on public.invites for insert to authenticated
with check (creator_id = auth.uid() and public.has_server_permission(server_id, 'create_invites'));
create policy "invites_delete_manager" on public.invites for delete to authenticated
using (public.has_server_permission(server_id, 'create_invites'));

drop policy if exists "direct_messages_insert" on public.direct_messages;
create policy "direct_messages_insert" on public.direct_messages for insert to authenticated
with check (
  author_id = auth.uid() and public.is_direct_member(conversation_id)
  and public.reply_belongs_to_direct(reply_to_id, conversation_id)
);

grant execute on function public.has_server_permission(uuid, text, uuid) to authenticated;
grant execute on function public.create_server_role(uuid, text, text, jsonb) to authenticated;
grant execute on function public.update_server_role(uuid, text, text, integer, jsonb) to authenticated;
grant execute on function public.delete_server_role(uuid) to authenticated;
grant execute on function public.assign_server_role(uuid, uuid, uuid) to authenticated;
grant execute on function public.remove_server_role(uuid, uuid, uuid) to authenticated;
grant execute on function public.kick_server_member(uuid, uuid, text) to authenticated;
grant execute on function public.ban_server_member(uuid, uuid, text) to authenticated;
grant execute on function public.unban_server_member(uuid, uuid) to authenticated;
grant execute on function public.issue_voice_command(uuid, uuid, text, uuid) to authenticated;
grant execute on function public.reply_belongs_to_channel(uuid, uuid) to authenticated;
grant execute on function public.reply_belongs_to_direct(uuid, uuid) to authenticated;

revoke all on function public.write_audit(uuid, text, uuid, text, text, jsonb) from public;
revoke all on function public.ensure_everyone_role(uuid) from public;
revoke all on function public.member_hierarchy(uuid, uuid) from public;
revoke all on function public.can_act_on_member(uuid, uuid, uuid) from public;

do $$
declare relation_name text;
begin
  foreach relation_name in array array['server_roles', 'member_roles', 'server_bans', 'audit_logs', 'voice_commands'] loop
    if not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = relation_name
    ) then
      execute format('alter publication supabase_realtime add table public.%I', relation_name);
    end if;
  end loop;
end $$;
